---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-env
  namespace: riot-im
  annotations:
data:
  SYNAPSE_SERVER_NAME: "riot.vk8s.io"
  SYNAPSE_REPORT_STATS: "yes"
  SYNAPSE_NO_TLS: "yes"
  POSTGRES_HOST: "postgresql-svc"
  POSTGRES_PASSWORD: "matrix"
  POSTGRES_USER: "matrix"
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: riot-im
  annotations:
spec:
  selector:
    app: synapse
  type: ClusterIP
  ports:
  - name: http
    targetPort: 8008
    port: 80
  - name: federation
    port: 8448
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: riot-im
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      initContainers:
        - name: init-synapse
          image: matrixdotorg/synapse:latest
          args: ['generate']
          envFrom:
            - configMapRef:
                name: synapse-env
          volumeMounts:
            - name: synapse-data
              mountPath: /data
      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          ports:
            - containerPort: 8008
              name: http
            - containerPort: 8448
              name: federation
          envFrom:
            - configMapRef:
                name: synapse-env
          volumeMounts:
            - name: synapse-data
              mountPath: /data
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
      volumes:
        - name: synapse-data
          emptyDir: {}
